#!/usr/bin/env python3
"""Create offline credentials for mutually authenticated Noise IK; never flashes hardware."""
import argparse
import base64
import json
import os
import stat
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey

PROTO = "Noise_IK_25519_ChaChaPoly_SHA256"
KEY_LEN = 32


def _private_bytes(key: X25519PrivateKey) -> bytes:
    return key.private_bytes(
        serialization.Encoding.Raw,
        serialization.PrivateFormat.Raw,
        serialization.NoEncryption(),
    )


def _public_bytes(key: X25519PrivateKey) -> bytes:
    return key.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )


def _array(name: str, value: bytes) -> str:
    if len(value) != KEY_LEN:
        raise ValueError("invalid key length")
    rows = ", ".join(f"0x{byte:02x}" for byte in value)
    return f"static const uint8_t {name}[32] = {{ {rows} }};"


def _firmware_header(device_private: bytes, authorized_initiator_public: bytes) -> str:
    return "\n".join((
        "/* Generated by tools/noise_ik_provision.py. Keep private; never commit. */",
        "#ifndef PICO_BRIDGE_NOISE_IK_KEYS_H",
        "#define PICO_BRIDGE_NOISE_IK_KEYS_H",
        "#include <stdint.h>",
        _array("PICO_BRIDGE_DEVICE_STATIC_PRIVATE", device_private),
        _array("PICO_BRIDGE_AUTHORIZED_INITIATOR_PUBLIC", authorized_initiator_public),
        "#endif",
        "",
    ))


def generate_bundle() -> dict:
    """Generate distinct device/initiator identity material entirely offline."""
    device = X25519PrivateKey.generate()
    initiator = X25519PrivateKey.generate()
    return {
        "firmware_header": _firmware_header(_private_bytes(device), _public_bytes(initiator)),
        "host_identity": {
            "schema": 1,
            "protocol": PROTO,
            "initiator_private_b64": base64.b64encode(_private_bytes(initiator)).decode("ascii"),
            "device_public_b64": base64.b64encode(_public_bytes(device)).decode("ascii"),
        },
    }


def b64decode_key(value: str) -> bytes:
    if not isinstance(value, str):
        raise ValueError("invalid key encoding")
    try:
        decoded = base64.b64decode(value.encode("ascii"), validate=True)
    except (ValueError, UnicodeError) as exc:
        raise ValueError("invalid key encoding") from exc
    if len(decoded) != KEY_LEN:
        raise ValueError("invalid key length")
    return decoded


def header_key(header: str, name: str) -> bytes:
    import re
    match = re.search(rf"{name}\[32\] = \{{([^}}]+)\}};", header)
    if match is None:
        raise ValueError("missing header key")
    values = re.findall(r"0x([0-9a-fA-F]{2})", match.group(1))
    if len(values) != KEY_LEN:
        raise ValueError("invalid header key")
    return bytes.fromhex("".join(values))


def write_bundle(directory: Path, bundle: dict) -> None:
    """Create an exclusive 0700 directory under a trusted private parent."""
    directory = Path(directory)
    if directory.name in ("", ".", ".."):
        raise ValueError("invalid output directory")
    parent_fd = os.open(directory.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    directory_fd = None
    created = []
    made_directory = False
    try:
        parent = os.fstat(parent_fd)
        if parent.st_uid != os.geteuid() or stat.S_IMODE(parent.st_mode) & 0o077:
            raise PermissionError("output parent must be private and owned by the current user")
        os.mkdir(directory.name, mode=0o700, dir_fd=parent_fd)
        made_directory = True
        directory_fd = os.open(directory.name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=parent_fd)
        files = {
            "noise_ik_keys.h": bundle["firmware_header"].encode("ascii"),
            "noise-ik.json": (json.dumps(bundle["host_identity"], indent=2) + "\n").encode("utf-8"),
        }
        for name, content in files.items():
            fd = os.open(name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600, dir_fd=directory_fd)
            created.append(name)
            with os.fdopen(fd, "wb") as stream:
                stream.write(content)
                stream.flush()
                os.fsync(stream.fileno())
        os.fsync(directory_fd)
        os.fsync(parent_fd)
    except BaseException:
        if directory_fd is not None:
            for name in created:
                os.unlink(name, dir_fd=directory_fd)
        if made_directory:
            os.rmdir(directory.name, dir_fd=parent_fd)
        raise
    finally:
        if directory_fd is not None:
            os.close(directory_fd)
        os.close(parent_fd)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create private Noise IK enrollment files; does not flash hardware.")
    parser.add_argument("--out", required=True, type=Path, help="new directory under an existing private 0700 parent")
    args = parser.parse_args()
    try:
        write_bundle(args.out, generate_bundle())
    except (ValueError, OSError, PermissionError):
        print("Provisioning failed: require a new directory under a private writable parent.", file=sys.stderr)
        return 1
    print("Created private Noise IK enrollment files. No hardware was changed and no key material was printed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
